# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: 'en-US'
title: iamhasime
email: hasime@alwayz.in
description: >- # this means to ignore newlines until "baseurl:"
  A builder's journey through entrepreneurship, technology, and life
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamhasime.com"  # Added https:// for secure connection
twitter_username: iamhasime
github_username:  daVincere

# Build settings
theme: minimal-mistakes-jekyll

# to enable toggle between dark and default theme [ source: https://github.com/mmistakes/minimal-mistakes/discussions/2033#discussioncomment-257421 ]
minimal_mistakes_skin: "dirt"
minimal_mistakes_skin2: "dark"

# Additional site features
search: true  # Enable site search
lunr:
  search_within_pages: true

# Analytics (optional)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-048N04377K"
    anonymize_ip: true

# Site Footer
footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/iamhasime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/iamhasime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daVincere"

# Author profile
author:
  name: "Hardeep Singh Mehra"
  avatar: "/assets/images/hasime.jpg"
  bio: "Builder"
  location: "Bangalore, India"
  links:
    - label: "X/Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/iamhasime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/iamhasime"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/iamhasime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daVincere"

# Reading time settings
words_per_minute: 200

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# SEO Related
twitter:
  username: iamhasime
social:
  type: Person
  links:
    - "https://twitter.com/iamhasime"
    - "https://linkedin.com/in/iamhasime"
    - "https://github.com/daVincere"

# Plugins
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Defaults (keep your existing defaults)
defaults:
  # home
  - scope:
      path: ""
    values:
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      # classes: wide
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


