# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: 'en-US'
title: iamhasime
email: hasime@alwayz.in
description: >- # this means to ignore newlines until "baseurl:"
  A record of journey of a wannabe entrepreneur
baseurl: "" # the subpath of your site, e.g. /blog
url: "iamhasime.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamhasime
# github_username:  daVincere

# Build settings
theme: minimal-mistakes-jekyll

# to enable toggle between dark and default theme [ source: https://github.com/mmistakes/minimal-mistakes/discussions/2033#discussioncomment-257421 ]
minimal_mistakes_skin: "dirt"
minimal_mistakes_skin2: "dark"

plugins:
  - jekyll-feed
  - jemoji

defaults:
  # home
  - scope:
      path: ""
    values:
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      # classes: wide
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false

author:
  name: "Hardeep Singh Mehra"
  avatar: "/assets/images/hasime.jpg"
  bio: "_wannabe_ **entrepreneur** who acts as a product guy" # Note: Markdown is allowed
  location: "Bangalore, India"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/iamhasime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/iamhasime"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/iamhasime"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
