# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
locale: 'en-US'
title: iamhasime
email: hasime@alwayz.in
description: >-
  A builder's journey through entrepreneurship, technology, and life
url: "https://iamhasime.com"
baseurl: "" # the subpath of your site, e.g. /blog

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
minimal_mistakes_skin2: "dark"

# Site features
search: true
lunr:
  search_within_pages: true
words_per_minute: 200
paginate: 10
paginate_path: /page:num/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-048N04377K"
    anonymize_ip: true

# Author profile
author:
  name: "Hardeep Singh Mehra"
  avatar: "/assets/images/hasime.png"
  bio: "Builder in AI"
  location: "Bangalore, India"
  links:
    - label: "X/Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/iamhasime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/iamhasime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daVincere"
    - label: "Newsletter"
      icon: "fas fa-fw fa-link"
      url: "https://thisweekinaiclub.substack.com/"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/iamhasime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/iamhasime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daVincere"
    - label: "Newsletter"
      icon: "fas fa-fw fa-link"
      url: "https://thisweekinaiclub.substack.com/"

# Social Sharing
twitter:
  username: "iamhasime"
  card: summary_large_image

og_image: "/assets/images/hasime.png"
social:
  type: "Person"
  links:
    - "https://x.com/iamhasime"
    - "https://linkedin.com/in/iamhasime"
    - "https://thisweekinaiclub.substack.com/"

# Plugins
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      share: true
  
  - scope:
      path: "_mental-models"
      type: mental-models
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  mental-models:
    output: true
    permalink: /:collection/:title/
